# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(max_length=255)),
                ('inspection_id', models.CharField(max_length=255)),
                ('risk_category', models.CharField(max_length=255)),
                ('inspection_url', models.TextField()),
                ('critical', models.IntegerField(default=0)),
                ('noncritical', models.IntegerField(default=0)),
                ('critical_corrected_on_site', models.IntegerField(default=0)),
                ('noncritical_corrected_on_site', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.TextField()),
                ('observation', models.TextField()),
                ('dcmr', models.TextField()),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.Inspection')),
            ],
        ),
    ]
