# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_date_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_date_out',
            field=models.DateTimeField(null=True),
        ),
    ]
