# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20170511_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='inspection_date_in',
            new_name='time_in',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='inspection_date_out',
            new_name='time_out',
        ),
    ]
