# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('permit_id', models.CharField(max_length=255)),
                ('quadrant', models.CharField(max_length=2, null=True)),
                ('address', models.TextField(null=True)),
                ('ward', models.CharField(max_length=255, null=True)),
                ('restaurant_type', models.CharField(max_length=255, null=True)),
                ('inspection_url', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
